-- 1. TABLA: users
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    pinHash VARCHAR(255) NOT NULL,
    avatar VARCHAR(255) NOT NULL,
    color VARCHAR(50) NOT NULL DEFAULT '#A6435A',
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 2. TABLA: shopping
CREATE TABLE IF NOT EXISTS shopping (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    quantity VARCHAR(100),
    category VARCHAR(100) DEFAULT 'Mercado',
    addedBy VARCHAR(255),
    bought TINYINT(1) NOT NULL DEFAULT 0, -- Usamos TINYINT(1) para booleanos (0 o 1)
    imageUrl VARCHAR(1024) DEFAULT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 3. TABLA: debts
CREATE TABLE IF NOT EXISTS debts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    `from` VARCHAR(255) NOT NULL, -- 'from' es palabra reservada, usamos comillas invertidas (backticks)
    `to` VARCHAR(255) NOT NULL, -- 'to' también es palabra reservada en algunos contextos
    amount DECIMAL(10, 2) NOT NULL DEFAULT 0.00, -- DECIMAL es ideal para dinero
    description TEXT,
    paid TINYINT(1) NOT NULL DEFAULT 0,
    paidAt TIMESTAMP NULL DEFAULT NULL,
    imageUrl VARCHAR(1024) DEFAULT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 4. TABLA: wishlist
CREATE TABLE IF NOT EXISTS wishlist (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(10, 2),
    link VARCHAR(512),
    priority VARCHAR(50) NOT NULL DEFAULT 'media',
    wantedBy VARCHAR(255),
    achieved TINYINT(1) NOT NULL DEFAULT 0,
    imageUrl VARCHAR(1024) DEFAULT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 5. TABLA: events
CREATE TABLE IF NOT EXISTS events (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    date DATE NOT NULL, -- Tipo DATE real en lugar de TEXT
    recurringYearly TINYINT(1) NOT NULL DEFAULT 1,
    notes TEXT,
    imageUrl VARCHAR(1024) DEFAULT NULL,
    createdBy VARCHAR(255),
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 6. TABLA: appointments
CREATE TABLE IF NOT EXISTS appointments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    date DATE NOT NULL,
    time TIME, -- Tipo TIME real
    location VARCHAR(255),
    notes TEXT,
    imageUrl VARCHAR(1024) DEFAULT NULL,
    createdBy VARCHAR(255),
    done TINYINT(1) NOT NULL DEFAULT 0,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 7. TABLA: notes
CREATE TABLE IF NOT EXISTS notes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    message TEXT NOT NULL,
    fromPerson VARCHAR(255),
    color VARCHAR(50),
    imageUrl VARCHAR(1024) DEFAULT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 8. TABLA: gallery
CREATE TABLE IF NOT EXISTS gallery (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255),
    imageUrl VARCHAR(1024) NOT NULL,
    description TEXT,
    createdBy VARCHAR(255),
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)